language: minimal
sudo: required
dist: trusty
os:
  - linux
  - osx
addons:
  homebrew:
    packages:
      - autoconf
      - automake
      - gnutls
      - texinfo
cache:
- directories:
  - "$HOME/emacs"
matrix:
  fast_finish: true
  allow_failures:
  - env: EMACS_VERSION=snapshot
env:
  global:
    - EMAKE_SHA1=7c2fdc5b5d911c219710ac7560db182f39a5d605
    - EMACS_DIR=$HOME/emacs
    - EMACS=$HOME/emacs/src/emacs
  matrix:
    - EMACS_VERSION=25.1
    - EMACS_VERSION=25.2
    - EMACS_VERSION=25.3
    - EMACS_VERSION=26.1
    - EMACS_VERSION=snapshot
before_install:
  - make setup
  - wget "https://raw.githubusercontent.com/vermiculus/emake.el/${EMAKE_SHA1}/emake.mk"
install:
  - make install
script:
  - time make travis-script
