language: emacs-lisp
sudo: required
dist: trusty
cache:
- directories:
  - "$HOME/emacs"
matrix:
  fast_finish: true
  allow_failures:
  - env: EMACS_VERSION=snapshot
env:
  matrix:
  - EMACS_VERSION=25.1
  - EMACS_VERSION=25.2
  - EMACS_VERSION=25.3
  - EMACS_VERSION=snapshot
before_install:
- make setup
install:
- make install
script:
- make test                     # test uncompiled
- make compile                  # test compilation
- make test                     # test compiled
